# Generated by Django 2.2.1 on 2019-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(choices=[(1, 'To Be Validated'), (2, 'Validated'), (3, 'Solved')], default=1)),
                ('category', models.IntegerField(choices=[(1, 'Construction'), (2, 'Special Event'), (3, 'Incident'), (4, 'Weather Condition'), (5, 'Road Condition')])),
            ],
        ),
    ]
