# Generated by Django 2.2.1 on 2019-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-update_date',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
