# Generated by Django 2.2.1 on 2019-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20190504_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CON', 'Construction'), ('SPE', 'Special Event'), ('INC', 'Incident'), ('WEC', 'Weather Condition'), ('ROC', 'Road Condition')], max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('TBV', 'To Be Validated'), ('VAL', 'Validated'), ('SOL', 'Solved')], default='TBV', max_length=3),
        ),
    ]
