# Generated by Django 2.2.1 on 2019-05-04 15:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20190504_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='localization',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
